version: '3.8'
services:
  app:
    build: .
    container_name: boxed_clean
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/boxed-clean
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boxed-clean
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: